# Generated by Django 4.1.1 on 2022-09-24 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='텍스트')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.audio')),
            ],
            options={
                'db_table': 'texts',
            },
        ),
    ]
