# Generated by Django 4.1.1 on 2022-09-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_audio_text_remove_user_name_audio_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='idx',
            field=models.IntegerField(verbose_name='텍스트 인덱스'),
        ),
    ]
