# Generated by Django 4.1.1 on 2022-09-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_audio_text_remove_user_name_audio_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
